id: P008257
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 13:11:22.583112
source_metadata:
  id: bdr:W21921
  title: སྨན་སྦྱོར་ལེགས་བསྒྲིགས་ཡང་གསལ་སྒྲོན་མེ།
  author: ''
  volumes:
    9fbce4ee1f3a4830abad37dac6be7890:
      image_group_id: I1KG12511
      title: ''
      volume_number: 1
      total_pages: 340
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
